import type { Metadata } from "next";
import { Plus_Jakarta_Sans } from "next/font/google";
import "./globals.css";
import Providers from "./providers";
import { SupabaseProvider } from "@/providers/supabase-provider";
import { Toaster } from "@/components/ui/sonner";

import { createClient } from "@/lib/supabase/server";
import { ThemeProvider } from "@/components/dark-mode-ui/theme-provider";
const plusJakartaSans = Plus_Jakarta_Sans({
  subsets: ["latin"],
  weight: ["200", "300", "400", "500", "600", "700", "800"], // gunakan variable font
  variable: "--font-jakarta", // CSS variable untuk digunakan di Tailwind atau style
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${plusJakartaSans.variable} antialiased`}>
        <ThemeProvider defaultTheme="light">
          <Providers>
            <Toaster richColors position="top-right" />
            {children}
          </Providers>
        </ThemeProvider>
      </body>
    </html>
  );
}
